/*    Atech
 *    Copyright (C) 2008  l & k
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Report.java
 *
 * Created on April 1, 2008, 8:43 PM
 */

package Atech;

import LibAtech.InformationUpdate;
import java.io.File;
import javax.swing.AbstractListModel;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author  l
 */
public class Report extends javax.swing.JInternalFrame {
    
    InformationUpdate atechDB;
    Main atechMain;
        
    String reportSource;
    String [] fileList;
    String folder = "Report";
    
    ListSelectionListener l = new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent evt) {
                reportSource = jlReport.getSelectedValue().toString();
                jbViewReport.setEnabled(true);
            }
    };
    AbstractListModel model;
    /** Creates new form Report */
    public Report(InformationUpdate atechDB,Main atechMain) {
        this.atechDB=atechDB;
        this.atechMain=atechMain;
        initComponents();
    }
    JDesktopPane jdp;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jlReport = new javax.swing.JList();
        jbViewReport = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Report");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jlReport.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jlReport);

        jbViewReport.setText("View Report");
        jbViewReport.setEnabled(false);
        jbViewReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbViewReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbViewReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbViewReport)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jbViewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbViewReportActionPerformed
    displayReport();
}//GEN-LAST:event_jbViewReportActionPerformed

private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
    jlReport.removeListSelectionListener(l);
    
    File dir = new File(folder);
    fileList = dir.list();
    
    if (fileList != null) {
       model = new AbstractListModel() {
                String[] strings = fileList;
                public int getSize() { 
                    return strings.length; 
                }
                public Object getElementAt(int i) { 
                    return strings[i]; 
                }
       };
    } 
    jlReport.setModel(model);
    jlReport.addListSelectionListener(l);
    
}//GEN-LAST:event_formInternalFrameActivated
JInternalFrame jif;
private void displayReport(){
   try { 
            jif = new DisplayReport(atechDB, folder+"/"+reportSource);
            atechMain.jdp.add(jif, new Integer(5));
            jif.setBounds(0, 0, 0, 0);
            jif.pack();
            jif.setMaximum(true);
            jif.setTitle(reportSource);
            jif.setVisible(true);
            jif.show();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,ex.getMessage());
            return;
        }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbViewReport;
    private javax.swing.JList jlReport;
    // End of variables declaration//GEN-END:variables

}
